### ISSUE TITLE
Error with the command node_modules/.bin/testrpc 

### ISSUE THREAD

**Issue by n1c01a5** [asseth/dao1901#8]
When I run the command `node_modules/.bin/testrpc`, I have this error :
```
/tmp/dao1901/node_modules/ethereumjs-vm/lib/index.js:29
function VM (opts = {}) {
                  ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/tmp/dao1901/node_modules/ethereumjs-vm/index.js:1:80)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

Any idea ?

PS to run the environment with `docker`:
```
docker run -it --rm node:4 bin/bash
cd /tmp/
git clone https://github.com/asseth/dao1901.git
cd dao1901/
npm i
node_modules/.bin/testrpc
```

**Comment by n1c01a5** [comment]
The bug is about the node version.
It's works with `docker run -it --rm node:7 bin/bash`.

**Comment by Janaka-Steph** [comment]
As of version 3.0.2, testrpc requires at least Node 6.9.1 to run - this is because the ethereumjs-vm@2.0.1 dependency is now shipping using ES2015 language features.

**Comment by amithanamakkanavar** [comment]
Even I am facing the same issue. 
I am getting the following information
$ node -v 
v5.12.0
$ nodejs -v 
v6.10.0
and truffle is installed properly.  problem is with testrpc.
